### ISSUE TITLE
代码复现出现问题

### ISSUE THREAD

**Issue by ChihungSan** [thunlp/ONION#5]
我在复现代码的过程中出现如下错误，请问有什么号的解决办法么？
Traceback (most recent call last):
  File "./experiments/test_defense.py", line 144, in <module>
    all_PPL = get_PPL(orig_poison_data)
  File "./experiments/test_defense.py", line 49, in get_PPL
    single_sent_PPL.append(LM(processed_sent))
  File "E:\ONION\experiments\gptlm.py", line 52, in __call__
    ipt = self.tokenizer(sent,return_tensors="pt", verbose=False,)
TypeError: 'GPT2TokenizerFast' object is not callable

**Comment by Yangyi-Chen** [comment]
你好， 感谢对我们工作的关注。 

这个错误可能是由于 Huggingface 版本号不同所导致的，可以考虑将Huggingface 版本适当回退。 

除此之外，我们推荐使用我们的工具包 OpenBackdooor： https://github.com/thunlp/OpenBackdoor  来完成相关 攻防算法的实现，  这个工具包经过比较多的测试，也投入更多的经历去维护。

**Comment by elegant228** [comment]
> 
请问如何修改Huggingface的 版本号啊？
